project_name: jntpdn
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  skip: false
  sort: ''
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-next"
source:
  enabled: true
  format: 'tar.gz'
  name_template: '{{ .ProjectName }}-{{ .Version }}'
