name: Checks on_push

on:
  push:
    branches:
      - "*"
    tags:
      - "!v*.*.*"
env:
  checkout_dir: "go/src/github.com/deogracia/jntpdn"
jobs:
  checks:
    name: run some checks
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
#        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            GOPATH: c:\gopath
          - os: ubuntu-latest
          - os: macos-latest
    steps:
    - name: Windows - Define and add GOPATH to PATH
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
          setx PATH "$env:path;c:\gopath\bin" -m
          echo "GOPATH=${GITHUB_WORKSPACE}/go" >> ${GITHUB_ENV}
          echo "c:\gopath\bin" >> ${GITHUB_PATH}
    - name: Non Windows - Define and add GOPATH to PATH
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
          echo "GOPATH=${GITHUB_WORKSPACE}/go" >> ${GITHUB_ENV}
          echo "${GITHUB_WORKSPACE}/go/bin" >> ${GITHUB_PATH}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: "${{env.checkout_dir}}"
    - name: Run ci target
      run:  |
          cd $GITHUB_WORKSPACE/$checkout_dir
          dir env: || env
          go install -i github.com/securego/gosec/cmd/gosec
          go install -i github.com/mitchellh/gox
          make ci
    - name: Build BSD artefacts
      run: |
          cd $GITHUB_WORKSPACE/$checkout_dir
          make build_bsd
