name: Checks on_push

on: [push]

jobs:
  checks:
    name: run some checks
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get go deps
      run:  |
          make install_deps
          go install -i github.com/securego/gosec/cmd/gosec
    - name: Check go code fmt
      run:  make check_fmt
    - name: Check go vet
      run:  make vet
    - name: Run gosec
      run:  |
          echo ${GOPATH}
          make security
      
