name: Checks on_push

on: [push]
#env:
#  GOPATH: $GITHUB_WORKSPACE/go
#  PATH:   $GOPATH:$PATH
jobs:
  checks:
    name: run some checks
    runs-on: ubuntu-18.04
    steps:
    - name: echo path 1
      run: echo $PATH
    - name: Define and add GOPATH top PATH
      run: |
          echo "::set-env name=GOPATH::${GITHUB_WORKSPACE}/go"
          echo "::add-path::${GOPATH}/bin"
          echo ${GOPATH}
          echo ${PATH}
    - name: echo path 2
      run: echo $PATH
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: $GOPATH/src/github.com/deogracia/jntpdn
    - name: Get go deps
      run:  |
          make install_deps
          go install -i github.com/securego/gosec/cmd/gosec
    - name: Check go code fmt
      run:  make check_fmt
    - name: Check go vet
      run:  make vet
    - name: Run gosec
      run:  make security
      
