name: Checks on_push

on: [push]

jobs:
  checks:
    name: run some checks
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: where am I
      run:  |
          env
          pwd
          ls -lha
          ls -lha ..
    - name: Check go code fmt
      run:  make check_fmt
    - name: Check go vet
      run:  make vet
      
