name: Checks on_push

on: [push]
env:
  checkout_dir: "go/src/github.com/deogracia/jntpdn"
#  GOPATH: "$GITHUB_WORKSPACE/go"
#  PATH:   "$GOPATH:$PATH"
jobs:
  checks:
    name: run some checks
    runs-on: ubuntu-18.04
    steps:
    - name: Define and add GOPATH top PATH
      run: |
          echo "::set-env name=GOPATH::${GITHUB_WORKSPACE}/go"
          echo "::add-path::${GITHUB_WORKSPACE/go/bin"
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${checkout_dir}
    - name: Get go deps
      run:  |
          echo $PATH
          ls -lhar $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/$checkout_dir
          make install_deps
          go install -i github.com/securego/gosec/cmd/gosec
    - name: Check go code fmt
      run:  make check_fmt
    - name: Check go vet
      run:  make vet
    - name: Run gosec
      run:  make security
      
