---
name: Checks on_push

on:
  push:
    branches:
      - "*"
    tags:
      - "!v*.*.*"
env:
  checkout_dir: "go/src/github.com/deogracia/jntpdn"
jobs:
  windows_checks:
    name: windows-latest - checks & build
    runs-on: windows-latest
    strategy:
      matrix:
        go: ['1.15']
    steps:
      - name: setup-go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: go version
        run: go version
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{env.checkout_dir}}"
      - name: Run ci target
        shell: bash
        run: |
            PATH="/$(go env GOPATH | sed 's/\\/\//g'| sed 's/://' )/bin":$PATH
            go get github.com/securego/gosec/cmd/gosec
            which gosec
            go get github.com/mitchellh/gox
            which gox
            go get golang.org/x/lint/golint
            which golint
            go get github.com/fzipp/gocyclo/cmd/gocyclo
            which gocyclo
            cd $GITHUB_WORKSPACE/$checkout_dir
            make ci_windows
      - name: Upload codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
          files: coverage.out
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-latest - generated executables
          path: ${{ github.workspace }}/${{ env.checkout_dir }}/output

  others-os_checks:
    name: ${{ matrix.os }} - checks & build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.15']
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: setup-go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: go version
        run: go version
      - name: Define and add GOPATH to PATH
        run: |
            echo "GOPATH=${GITHUB_WORKSPACE}/go" >> ${GITHUB_ENV}
            echo "${GITHUB_WORKSPACE}/go/bin" >> ${GITHUB_PATH}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{env.checkout_dir}}"
      - name: Run ci target
        run: |
            go get github.com/securego/gosec/cmd/gosec
            go get github.com/mitchellh/gox
            go get golang.org/x/lint/golint
            go get github.com/fzipp/gocyclo/cmd/gocyclo
            cd $GITHUB_WORKSPACE/$checkout_dir
            make ci
      - name: Build BSD artefacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
            cd $GITHUB_WORKSPACE/$checkout_dir
            make build_bsd
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }} - generated executables
          path: ${{ github.workspace }}/${{ env.checkout_dir }}/output
